# Generated by Django 5.1.15 on 2026-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("issuer", models.CharField(max_length=180)),
                ("issued_date", models.DateField()),
                ("credential_url", models.URLField(blank=True)),
                ("image", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-issued_date"],
            },
        ),
    ]
