export const projects = [
  {
    title: "Vendas.co.ke",
    kind: "E-Commerce",
    mark: "01",
    style: "",
    description: "A live e-commerce platform hosted at vendas.co.ke, showcasing full-stack development and deployment expertise.",
    tags: ["Full-Stack", "E-Commerce", "Web Hosting", "Production"],
  },
  {
    title: "SwiftSend",
    kind: "Fintech",
    mark: "02",
    style: "alt",
    description: "A cross-border money transfer platform leveraging Stellar blockchain for fast, low-cost remittances.",
    tags: ["React", "Django", "Stellar", "Python"],
  },
  {
    title: "ncAGENTS",
    kind: "AI Platform",
    mark: "03",
    style: "gold",
    description: "An AI agent management platform for creating, deploying, and collaborating with intelligent AI agents.",
    tags: ["TypeScript", "React", "Tailwind", "Framer Motion"],
  },
  {
    title: "TrustMall",
    kind: "Blockchain",
    mark: "04",
    style: "",
    description: "A decentralized escrow-powered marketplace enabling secure and transparent trade between buyers and sellers.",
    tags: ["TypeScript", "Next.js", "Solidity", "Stellar"],
  },
  {
    title: "NGO Website",
    kind: "Non-Profit",
    mark: "05",
    style: "",
    description: "A website for Ivy Eco Solutions, a non-profit organization committed to uplifting lives through sustainable programs.",
    tags: ["JavaScript", "HTML", "CSS", "React"],
  },
  {
    title: "Turing Insurance",
    kind: "Insurance",
    mark: "06",
    style: "",
    description: "An MVP for Turing Insurance, a partner in simplifying insurance claims.",
    tags: ["JavaScript", "React", "HTML", "CSS"],
  },
  {
    title: "Hopkins Crescent Hospital",
    kind: "Healthcare",
    mark: "07",
    style: "",
    description: "An enhanced webpage for Hopkins Crescent Hospital.",
    tags: ["JavaScript", "HTML", "CSS", "React"],
  },
  {
    title: "COD-K Political Party",
    kind: "Political",
    mark: "08",
    style: "",
    description: "A website for COD-K, a progressive political movement championing inclusive governance and national transformation.",
    tags: ["JavaScript", "HTML", "CSS", "React"],
  },
  {
    title: "Madam President Portfolio",
    kind: "Portfolio",
    mark: "09",
    style: "",
    description: "A portfolio for Madam President, Stellar East Africa.",
    tags: ["JavaScript", "HTML", "CSS", "React"],
  },
  {
    title: "Statistics & SQL Data Analysis",
    kind: "Data Analysis",
    mark: "10",
    style: "",
    description: "A comprehensive data analysis project covering statistics, probability, and SQL data preparation.",
    tags: ["Jupyter Notebook", "Python", "SQL", "Pandas"],
  },
];

export const skills = [
  "Python",
  "JavaScript",
  "TypeScript",
  "Django",
  "Next.js",
  "React",
  "PostgreSQL",
  "SQL",
  "Git & GitHub",
  "Data Analysis",
  "REST APIs",
  "Power BI",
  "Stellar",
  "Solidity",
  "Docker",
];
