import { NextResponse } from "next/server";

const projects = [
  {
    id: 1,
    title: "Vendas.co.ke",
    slug: "vendas-coke",
    summary: "A live e-commerce platform hosted at vendas.co.ke, showcasing full-stack development and deployment expertise.",
    description: "Vendas.co.ke is a fully functional e-commerce platform that demonstrates end-to-end development and deployment capabilities. The platform is live and serving real users, showcasing practical experience with production systems, domain hosting, and real-world problem solving.",
    image: "",
    technologies: ["Full-Stack", "E-Commerce", "Web Hosting", "Production"],
    highlights: ["Live production deployment", "Custom domain hosting", "Real-world user traffic", "End-to-end development"],
    status: "maintained",
    featured: true,
    repository_url: "",
    live_url: "https://vendas.co.ke",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    title: "SwiftSend",
    slug: "swiftsend",
    summary: "A cross-border money transfer platform leveraging Stellar blockchain for fast, low-cost remittances.",
    description: "SwiftSend is a fintech application that enables users to send money across borders using Stellar blockchain technology. The platform offers competitive exchange rates, near-instant settlements, and lower fees compared to traditional remittance services.",
    image: "",
    technologies: ["React", "Django", "Stellar", "Python", "JWT"],
    highlights: ["Stellar blockchain integration", "JWT authentication system", "Withdrawal tracking", "Transaction history", "Route-guarded protected pages"],
    status: "completed",
    featured: true,
    repository_url: "https://github.com/David-Moenga/SwiftSend1",
    live_url: "",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 3,
    title: "ncAGENTS",
    slug: "ncagents",
    summary: "An AI agent management platform for creating, deploying, and collaborating with intelligent AI agents.",
    description: "ncAGENTS is a comprehensive AI agent management platform that democratizes AI development. It provides tools for creating custom AI agents with advanced memory systems, multi-agent collaboration, voice interaction, and blockchain integration.",
    image: "",
    technologies: ["TypeScript", "React", "Tailwind CSS", "Framer Motion", "ElevenLabs", "Stellar"],
    highlights: ["AI agent creation and management", "Multi-agent collaboration", "Voice interaction (ElevenLabs)", "Blockchain wallet integration", "Agent marketplace"],
    status: "completed",
    featured: true,
    repository_url: "https://github.com/David-Moenga/Agend49",
    live_url: "",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 4,
    title: "TrustMall",
    slug: "trustmall",
    summary: "A decentralized escrow-powered marketplace enabling secure and transparent trade between buyers and sellers.",
    description: "TrustMall is a blockchain-based marketplace that uses escrow smart contracts to ensure secure transactions. Buyers can purchase goods with confidence, knowing their funds are held in escrow until the seller delivers.",
    image: "",
    technologies: ["TypeScript", "Next.js", "Solidity", "Stellar", "Tailwind CSS"],
    highlights: ["Smart contract-based escrow system", "Multi-cryptocurrency support", "Dispute resolution mechanism", "Real-time transaction tracking"],
    status: "completed",
    featured: true,
    repository_url: "https://github.com/David-Moenga/new_trustmall",
    live_url: "",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 5,
    title: "NGO Website - Ivy Eco Solutions",
    slug: "ngo-ivy-eco-solutions",
    summary: "A website for Ivy Eco Solutions, a non-profit organization committed to uplifting lives through sustainable programs.",
    description: "A complete website for Ivy Eco Solutions, a passionate non-profit organization committed to uplifting lives through sustainable programs in education, health, and community development.",
    image: "",
    technologies: ["JavaScript", "HTML", "CSS", "React"],
    highlights: ["Non-profit organization website", "Education and health programs", "Community development initiatives", "Responsive design"],
    status: "completed",
    featured: false,
    repository_url: "https://github.com/David-Moenga/NGO-SITE",
    live_url: "",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 6,
    title: "Turing Insurance",
    slug: "turing-insurance",
    summary: "An MVP for Turing Insurance, a partner in simplifying insurance claims.",
    description: "The structure MVP for Turing Insurance, a platform focused on simplifying insurance claims. The project demonstrates understanding of insurance workflows and user experience design.",
    image: "",
    technologies: ["JavaScript", "React", "HTML", "CSS"],
    highlights: ["Insurance claims simplification", "User experience design", "MVP development", "Workflow optimization"],
    status: "completed",
    featured: false,
    repository_url: "https://github.com/David-Moenga/Turing-Insurance",
    live_url: "",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 7,
    title: "Hopkins Crescent Hospital",
    slug: "hopkins-crescent-hospital",
    summary: "An enhanced webpage for Hopkins Crescent Hospital.",
    description: "An enhanced webpage for Hopkins Crescent Hospital, showcasing healthcare services and providing an improved user experience for patients and visitors.",
    image: "",
    technologies: ["JavaScript", "HTML", "CSS", "React"],
    highlights: ["Healthcare services showcase", "Enhanced user experience", "Patient information portal", "Responsive design"],
    status: "completed",
    featured: false,
    repository_url: "https://github.com/David-Moenga/Hopkins_crescent",
    live_url: "",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 8,
    title: "COD-K Political Party",
    slug: "cod-k-political-party",
    summary: "A website for COD-K, a progressive political movement championing inclusive governance and national transformation.",
    description: "A simple website for COD-K political party, a progressive political movement championing inclusive governance, human dignity, and national transformation.",
    image: "",
    technologies: ["JavaScript", "HTML", "CSS", "React"],
    highlights: ["Political party website", "Inclusive governance advocacy", "National transformation initiatives", "Community engagement"],
    status: "completed",
    featured: false,
    repository_url: "https://github.com/David-Moenga/COD_K",
    live_url: "",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 9,
    title: "Madam President Portfolio",
    slug: "madam-president-portfolio",
    summary: "A portfolio for Madam President, Stellar East Africa.",
    description: "A portfolio website for Madam President, Stellar East Africa, showcasing leadership initiatives and community impact.",
    image: "",
    technologies: ["JavaScript", "HTML", "CSS", "React"],
    highlights: ["Leadership portfolio", "Community impact showcase", "Stellar East Africa initiatives", "Professional branding"],
    status: "completed",
    featured: false,
    repository_url: "https://github.com/David-Moenga/madam_portfolio",
    live_url: "",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 10,
    title: "Statistics & SQL Data Analysis",
    slug: "statistics-sql-data-analysis",
    summary: "A comprehensive data analysis project covering statistics, probability, and SQL data preparation.",
    description: "An in-depth exploration of statistical methods, probability theory, and SQL data preparation techniques. This project demonstrates practical applications of statistical analysis on real-world datasets using Jupyter Notebooks.",
    image: "",
    technologies: ["Jupyter Notebook", "Python", "SQL", "Pandas", "Statistics"],
    highlights: ["Statistical analysis", "Probability theory", "SQL data preparation", "Data visualization"],
    status: "completed",
    featured: false,
    repository_url: "https://github.com/David-Moenga/statistics_sql_and_data_analysis",
    live_url: "",
    created_at: "2024-01-01T00:00:00Z",
  },
];

export async function GET(
  request: Request,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;
  const project = projects.find((p) => p.slug === slug);

  if (!project) {
    return NextResponse.json({ error: "Project not found" }, { status: 404 });
  }

  return NextResponse.json(project);
}
