export const projects = [
  {
    title: "TrustMall",
    kind: "Blockchain",
    mark: "01",
    style: "",
    description: "A decentralized escrow-powered marketplace enabling secure and transparent trade between buyers and sellers.",
    tags: ["TypeScript", "Next.js", "Solidity", "Stellar"],
  },
  {
    title: "SwiftSend",
    kind: "Fintech",
    mark: "02",
    style: "alt",
    description: "A cross-border money transfer platform leveraging Stellar blockchain for fast, low-cost remittances.",
    tags: ["React", "Django", "Stellar", "Python"],
  },
  {
    title: "CineScope",
    kind: "Web App",
    mark: "03",
    style: "gold",
    description: "A movie discovery app with trending titles, search, and personalized recommendations powered by TMDB API.",
    tags: ["React", "Vite", "TMDB API", "Appwrite"],
  },
  {
    title: "ncAGENTS",
    kind: "AI Platform",
    mark: "04",
    style: "",
    description: "An AI agent management platform for creating, deploying, and collaborating with intelligent AI agents.",
    tags: ["TypeScript", "React", "Tailwind", "Framer Motion"],
  },
];

export const skills = [
  "Python",
  "JavaScript",
  "TypeScript",
  "Django",
  "Next.js",
  "React",
  "PostgreSQL",
  "SQL",
  "Git & GitHub",
  "Data Analysis",
  "REST APIs",
  "Power BI",
  "Stellar",
  "Solidity",
  "Docker",
];
